package com.euler.project;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 * 
 * Expected value: 4613732
 * 
 * Logic: 
 * 0, 1, 1, 2, 3, 5
 * x  y  z
 *	  x  y  z
 *	     x  y  z
 *	        x  y  z
 *
 * So, in the loop:
 * x + y = z
 * x = y
 * y = z
 * 
 * */
public class Project2 {

	private static void fibonacci(int n) {
		int x = 0;
		int y = 1;
		int z;
		int sum = 0;

		System.out.println("Fibonacci sequence: ");
		do {
			z = x + y;
			x = y;
			y = z;		
			if (y % 2 == 0)
				sum += y;
			System.out.println(z);
			
		} while (y <= n);
		System.out.println("Sum: " + sum);
	}

	public static void main(String[] args) {
		fibonacci(4000000);
	}
}
